wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TR_SpecificationHashes.sha512                                             
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TR_PredefinedNames.pdf                                                    
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_EXP_VFB.pdf                                                               
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_RS_Main.pdf                                                               
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_RS_ProjectObjectives.pdf                                                  
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TR_Glossary.pdf                                                           
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_RS_Features.pdf                                                           
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TR_Methodology.pdf                                                        
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TR_TimingAnalysis.pdf                                                     
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_RS_Methodology.pdf                                                        
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_RS_MethodologyAndTemplatesGeneral.pdf                                     
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TR_AutosarModelConstraints.pdf                                            
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TR_InteroperabilityOfAutosarTools.pdf                                     
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_RS_InteractionWithBehavioralModels.pdf                                    
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TR_InteractionWithBehavioralModels.pdf                                    
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_RS_InteroperabilityOfAutosarTools.pdf                                     
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_RS_TimingExtensions.pdf                                                   
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_RS_ECUResourceTemplate.pdf                                                
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_RS_ECUConfiguration.pdf                                                   
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_RS_BSWModuleDescriptionTemplate.pdf                                       
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_RS_DiagnosticExtractTemplate.pdf                                          
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_RS_StandardizationTemplate.pdf                                            
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TR_FrancaIntegration.pdf                                                  
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_RS_SafetyExtensions.pdf                                                   
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_RS_FeatureModelExchangeFormat.pdf                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TR_GeneralBlueprintsSupplement.pdf                                        
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_RS_SoftwareComponentTemplate.pdf                                          
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_RS_SystemTemplate.pdf                                                     
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TPS_StandardizationTemplate.pdf                                           
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TPS_TimingExtensions.pdf                                                  
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TPS_GenericStructureTemplate.pdf                                          
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TPS_SystemTemplate.pdf                                                    
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TPS_ECUConfiguration.pdf                                                  
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TPS_FeatureModelExchangeFormat.pdf                                        
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TPS_SafetyExtensions.pdf                                                  
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TPS_DiagnosticExtractTemplate.pdf                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TPS_SoftwareComponentTemplate.pdf                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TPS_BSWModuleDescriptionTemplate.pdf                                      
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TR_XMLPersistenceRules.pdf                                                
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TPS_ECUResourceTemplate.pdf                                               
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TR_BSWModuleList.pdf                                                      
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_EXP_InterruptHandlingExplanation.pdf                                      
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_EXP_BSWDistributionGuide.pdf                                              
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_EXP_LayeredSoftwareArchitecture.pdf                                       
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_EXP_ErrorDescription.pdf                                                  
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_EXP_CDDDesignAndIntegrationGuideline.pdf                                  
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_BSWGeneral.pdf                                                        
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TR_BSWUMLModelModelingGuide.pdf                                           
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_EXP_ApplicationLevelErrorHandling.pdf                                     
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_BSWGeneral.pdf                                                        
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_FlashDriver.pdf                                                       
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_EEPROMDriver.pdf                                                      
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_MemoryHWAbstractionLayer.pdf                                          
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_MemoryServices.pdf                                                    
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_NVRAMManager.pdf                                                      
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_MemoryAbstractionInterface.pdf                                        
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_EEPROMAbstraction.pdf                                                 
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_EEPROMDriver.pdf                                                      
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_FlashDriver.pdf                                                       
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_FlashEEPROMEmulation.pdf                                              
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_StandardTypes.pdf                                                     
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_COM.pdf                                                               
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_SAEJ1939.pdf                                                          
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_NetworkManagement.pdf                                                 
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_Ethernet.pdf                                                          
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_Transformer.pdf                                                       
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_IPDUMultiplexer.pdf                                                   
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_CAN.pdf                                                               
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_XCP.pdf                                                               
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_FlexRay.pdf                                                           
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_SAEJ1939RequestManager.pdf                                            
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_COM.pdf                                                               
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_XCP.pdf                                                               
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_FlexRayNetworkManagement.pdf                                          
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_FlexRayTransceiverDriver.pdf                                          
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_EthernetDriver.pdf                                                    
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_LINStateManager.pdf                                                   
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_FlexRayDriver.pdf                                                     
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_EthernetInterface.pdf                                                 
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_TimeSyncOverEthernet.pdf                                              
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_CANInterface.pdf                                                      
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_EthernetSwitchDriver.pdf                                              
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_SAEJ1939NetworkManagement.pdf                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_TTCANInterface.pdf                                                    
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_TimeSyncOverCAN.pdf                                                   
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_CANNetworkManagement.pdf                                              
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_CANTransportLayer.pdf                                                 
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_EthernetStateManager.pdf                                              
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_SocketAdaptor.pdf                                                     
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_NetworkManagementInterface.pdf                                        
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_TcpIp.pdf                                                             
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_TimeSyncOverFlexRay.pdf                                               
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_CANDriver.pdf                                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_FlexRayStateManager.pdf                                               
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_COMBasedTransformer.pdf                                               
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_LINDriver.pdf                                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_SAEJ1939TransportLayer.pdf                                            
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_FlexRayISOTransportLayer.pdf                                          
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_LargeDataCOM.pdf                                                      
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_RTE.pdf                                                               
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_LINNetworkManagement.pdf                                              
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_PDURouter.pdf                                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_ServiceDiscovery.pdf                                                  
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_FlexRayInterface.pdf                                                  
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_COMManager.pdf                                                        
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_CommunicationStackTypes.pdf                                           
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_EthernetTransceiverDriver.pdf                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_LINInterface.pdf                                                      
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_LINTransceiverDriver.pdf                                              
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_FlexRayARTransportLayer.pdf                                           
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_TTCAN.pdf                                                             
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_Gateway.pdf                                                           
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_LIN.pdf                                                               
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_ASWS_TransformerGeneral.pdf                                               
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_TTCANDriver.pdf                                                       
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_IPDUMultiplexer.pdf                                                   
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_CANTransceiverDriver.pdf                                              
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_UDPNetworkManagement.pdf                                              
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_SOMEIPTransformer.pdf                                                 
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_CANStateManager.pdf                                                   
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_RTE.pdf                                                               
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_Diagnostic.pdf                                                        
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_FunctionInhibitionManager.pdf                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_DefaultErrorTracer.pdf                                                
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_DiagnosticCommunicationManager.pdf                                    
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_FunctionInhibitionManager.pdf                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_SAEJ1939DiagnosticCommunicationManager.pdf                            
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_DiagnosticEventManager.pdf                                            
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_DiagnosticOverIP.pdf                                                  
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_EXP_ModeManagementGuide.pdf                                               
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_Debugging.pdf                                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_ModeManagement.pdf                                                    
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_OS.pdf                                                                
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_DiagnosticLogAndTrace.pdf                                             
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_SynchronizedTimeBaseManager.pdf                                       
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_FreeRunningTimer.pdf                                                  
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_TimeService.pdf                                                       
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_TimeService.pdf                                                       
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_ECUStateManagerFixed.pdf                                              
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_DiagnosticLogAndTrace.pdf                                             
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_OCUDriver.pdf                                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_PortDriver.pdf                                                        
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_ADCDriver.pdf                                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_SPIHandlerDriver.pdf                                                  
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_ICUDriver.pdf                                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_SPALGeneral.pdf                                                       
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_MCUDriver.pdf                                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_DIODriver.pdf                                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_IOHWAbstraction.pdf                                                   
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_PWMDriver.pdf                                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_ECUStateManager.pdf                                                   
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_BSWModeManager.pdf                                                    
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_SynchronizedTimeBaseManager.pdf                                       
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_Debugging.pdf                                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_OS.pdf                                                                
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_SecureOnboardCommunication.pdf                                        
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_EXP_UtilizationOfCryptoServices.pdf                                       
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_EXP_FunctionalSafetyMeasures.pdf                                          
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_WatchdogDriver.pdf                                                    
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_CryptoServiceManager.pdf                                              
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_E2ETransformer.pdf                                                    
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_RAMTest.pdf                                                           
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_CRCLibrary.pdf                                                        
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_WatchdogDriver.pdf                                                    
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_SecureOnboardCommunication.pdf                                        
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_CryptoAbstractionLibrary.pdf                                          
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_WatchdogInterface.pdf                                                 
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_FlashTest.pdf                                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_IOHardwareAbstraction.pdf                                             
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_GPTDriver.pdf                                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_EXP_SafetyUseCase.pdf                                                     
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_FlashTest.pdf                                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_CoreTest.pdf                                                          
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_E2E.pdf                                                               
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TR_SafetyConceptStatusReport.pdf                                          
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_RAMTest.pdf                                                           
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_CoreTest.pdf                                                          
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_E2ELibrary.pdf                                                        
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_CryptoServiceManager.pdf                                              
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_WatchdogManager.pdf                                                   
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_DIODriver.pdf                                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_PortDriver.pdf                                                        
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_ADCDriver.pdf                                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_OCUDriver.pdf                                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_ICUDriver.pdf                                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_PWMDriver.pdf                                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_GPTDriver.pdf                                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_MCUDriver.pdf                                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_SPIHandlerDriver.pdf                                                  
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_PlatformTypes.pdf                                                     
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TR_SWCModelingGuide.pdf                                                   
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TR_AIMeasurementCalibrationDiagnostics.pdf                                
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_RS_SWCModeling.pdf                                                        
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TR_AIDesignPatternsCatalogue.pdf                                          
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_EXP_AIUserGuide.pdf                                                       
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_EXP_AIOccupantAndPedestrianSafety.pdf                                     
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_EXP_AIBodyAndComfort.pdf                                                  
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_EXP_AIHMIMultimediaAndTelematics.pdf                                      
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_EXP_AIChassis.pdf                                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_EXP_AIPowertrain.pdf                                                      
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_CompilerAbstraction.pdf                                               
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_MemoryMapping.pdf                                                     
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SRS_Libraries.pdf                                                         
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_IFLLibrary.pdf                                                        
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_BFXLibrary.pdf                                                        
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_MFXLibrary.pdf                                                        
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_MFLLibrary.pdf                                                        
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_IFXLibrary.pdf                                                        
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_SWS_EFXLibrary.pdf                                                        
wget --no-check-certificate  https://www.autosar.org/fileadmin/user_upload/standards/classic/4-2/AUTOSAR_TR_ReleaseOverviewAndRevHistory.pdf                                       